# Generated by Django 4.0.4 on 2022-05-02 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('0', 'B.Tech'), ('1', 'MCA'), ('2', 'M.Tech'), ('3', 'MBA')], default='B.Tech', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='enrolled_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
