# Generated by Django 4.0.4 on 2022-05-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
