# Generated by Django 4.0.4 on 2022-05-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_section_alter_profile_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profile_image',
        ),
    ]
