# Generated by Django 4.0.6 on 2022-07-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/default-avatar_r01tfd.jpg', null=True, upload_to='profile'),
        ),
    ]
