# Generated by Django 4.0.6 on 2022-07-17 08:00

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.CharField(default=profiles.models.random_about, max_length=200),
        ),
    ]
