# Generated by Django 4.0.6 on 2022-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('BTech', 'Bachelor of Technology'), ('MCA', 'Masters of Computer Application')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(choices=[('ECE', 'Electronics & Communication'), ('IT', 'Information & Technology'), ('EEE', 'Electrical and Electronics Engineering'), ('CSE', 'Computer Science Engineeering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=5, null=True),
        ),
    ]
